Fix undefined method `protect_from_forgery'
Problem
- NoMethodError
- undefined method `protect_from_forgery' for ApplicationRecord:Class

Reason
- Place the config codes inside application_record instead of
application_controller

Solution
- Move the codes to application_controller